### ISSUE TITLE
Any solution to the full manual mode for RasberryPi camera ?

### ISSUE THREAD

**Issue by rapitz** [raspberrypi/userland#151]
I am a real starter on this, but I need that mode for photometry. So far it seems that is quite difficult. Is there any hope ?

**Comment by ivannaz** [comment]
I think I still have an issue regarding full manual exposure. 

I can't keep "analog gain" and "digital gain" frozen at some specific - or minimum - values.

While I can specify exposure time and ISO, the camera still sets its analog and digital gain by itself. And it is bad at it! When the center and most of the area is dark, and only a corner have light, the analog and digital gains increase to the point of saturating this corner area. Perhaps, in some "automatic exposure" criteria, this is OK. But we are talking about manual exposure here, and there is nothing manual in this camera attempt of outsmarting me and destroying the scene details in the corner.

This is an example:
# raspistill -t 0 -set --shutter 10000 -awb off -awbg 1.0,1.0 -ISO 100
mmal: Exposure now 9977, analog gain 256/256, digital gain 640/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 256/256, digital gain 832/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1024/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1024/256, digital gain 512/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1024/256, digital gain 640/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1024/256, digital gain 704/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1792/256, digital gain 419/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1792/256, digital gain 428/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1968/256, digital gain 394/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 1968/256, digital gain 396/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 2016/256, digital gain 387/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 2016/256, digital gain 388/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 9977, analog gain 2016/256, digital gain 389/256
mmal: AWB R=256/256, B=256/256

And the corner scene is now saturated.

Is there a way to get the raw bayer data from the sensor? Or at least shut down any attempt to correct anything, and let _me_ specify the manual exposure I need? It would be great if we had "-ex manual", for instance. Can this be done through mmal?

Regards,

Ivan

**Comment by ethanol100** [comment]
Try adding -ev -24 to your command. This will try to reduce the gains to a minimum and should give you analog gain 256/256, digital gain 256/256.

Getting the raw sensor data will not be of much help for you. The analog gain is applied to the sensor and will change the raw bayer data too. There is the new possibility to get the raw bayer data, but it is fixed to a single value of shutter speed see https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=109137.

**Comment by ivannaz** [comment]
Thank you! It is a shame I have not tried the ev settings before - perhaps because I did not, and still does not, understand exactly what this -24 means, and why -25 is not so good. I glanced at the sources, but it seems that is setting is dealt only in gpu arena.

Now gains are, if not fixed, at least less variable, and corner saturation is less frequent.

 raspistill -t 0 -set --shutter 100 -awb off -awbg 1.0,1.0 -ISO 100 -ev -24
mmal: Exposure now 83, analog gain 256/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 83, analog gain 1024/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 83, analog gain 1792/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 83, analog gain 1968/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 83, analog gain 2016/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256
mmal: Exposure now 83, analog gain 2032/256, digital gain 256/256
mmal: AWB R=256/256, B=256/256

The digital gain seems locked, and while the analog gain is still uncontrolled, it needs really dark scenes to ramp up (notice the short exposure time). I still can induce corner saturation, but only in more extreme cases. In dimly lit scenes, with just a small bright object (say, a CCFT lamp), the analog gain goes up only when the object not at center - and adding "-mm matrix" improved that.

It is still not an strict manual exposure, but is close enough to be useful.

Thank you.

Regards,

Ivan

**Comment by 6by9** [comment]
EV is in 1/6ths of a stop, so -24 is -4 stops. If shutter speed hadn't been fixed, then it would also try adjusting that.
It can also be set as a MMAL_RATIONAL_T to explicitly set the number of stops in the range -4 to +4 (although the exposure mode will clip the max gain combination and shutter speed), but it is still in 1/6ths under the bonnet, so don't expect finer grained control.
ISO setting seems to be slightly odd that it does not obey it during preview, but should on a still capture. Not something I'm going to fiddle with as it is fiendishly complicated.

As @ethanol100 has said, yes you can now get to the raw data and do the lot yourself, but you need to understand the register settings.
Shutter time is covered in the unofficial datasheet that can be obtained from the internet, as is analogue gain. rawcam as checked in gives an exposure time of 36.403ms, and analogue gain of (I think) x2.18 - they were the values I happened to have to hand, and must confess to not having copied that bit from jbeale's I2C dumps. Line lengths for the various modes have been quoted on the forums before.
As mentioned on the thread there has been some work done on the Freescale i.MX6 platform to write a driver for OV5647, so www.viionsystems.com/UbuntuImages/ov5647_mipi.c might give some useful information for setting exposure time and gain to values of your choosing. I don't know where they got their information from, but it looks correct.

**Comment by ivannaz** [comment]
I hope the -ev -24 would be enough, and further measures unnecessary. Thank you.

I removed the default lens and installed an M12. Noticed something odd: While expecting an featureless and smooth image of a clean, uniformly lit paper sheet, the image shows all four corners brighter than the center image level. As if the sensor - or the GPU - were doing some sort of vignetting compensation of the original lens. Do you happen to know if the GPU does that? If it does, would the raw access bypass this correction?

**Comment by JamesH65** [comment]
Yes, the GPU has a lens shading correction table tuned to the original lens. Using raw will indeed bypass this - the data in raw is direct from the sensor, so the only setting of relevance will be the analog gain.

**Comment by spikedrba** [comment]
is there any solution/recommendation (other than using raw), to compensate/remove the shading correction if one uses a different lens?

**Comment by JamesH65** [comment]
No, afraid not. Best bet is to write your own lens shading code that compensates. Take the picture of the flat field, then work out what adjustments you need to make to get a resulting flat image, then apply as necessary.

**Comment by shrx** [comment]
Unfortunately I can't find the source, but if I remember correctly there were plans to have the camera use dynamic (i.e., lens-specific) color and brightness corrections, but I guess it was put on hold or deemed unfeasible.

**Comment by 6by9** [comment]
The dynamic lens shading algo is active, but only if you enable a statistics pass on stills capture - "-st" option in raspistill. Doing so also forces recomputing all AWB gains, so don't complain when "-awbg" then fails, and potentially AE digital gain.
Trying to integrate the fixes to run dynamic lens shading without needing a stats pass is still on my "to do" list, but the branch it was fixed on had significantly diverged from the Pi branch so the changes need significant rework. No longer working for Broadcom rather puts a damper on the time available to play with Pi firmware.

**Comment by spikedrba** [comment]
@JamesH65 bear with a noob if you can, any pointer of what I'd need to read up and understand in order to do that? or is this yet another case of completely missing the point and this being something requiring a ton of understanding and many months man hours to accomplish?

**Comment by shrx** [comment]
I wouldn't say months, but it's not straightforward:
http://en.wikipedia.org/wiki/Flat-field_correction
http://www.astronomie-und-internet.de/docs/Creating%20a%20Flatfield%20Calibrating%20Image.pdf

**Comment by 6by9** [comment]
There's no way to set your own lens shading tables into the ISP, so if you were to try calibrating it yourself, then you've got to implement the entire pipeline yourself. That is lots of work, or you've got to make use of someone else's pipe which is unlikely to be trivial, or realtime. 
IIRC Lens shading correction is done in the Bayer domain as you end up with tables for each of the 4 colour channels (the 2 greens are generally treated independently). I don't know what results you'll get trying to correct for that at the back end of the pipe.

**Comment by namorrellek** [comment]
has there been an update to disable lens compensation or load an individual compensation in the meantime?

**Comment by JamesH65** [comment]
Not that I am aware off. Any thoughts 6x9?

**Comment by 6by9** [comment]
As stated on the forums (https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=126220), no, there have been no changes to the lens shading arrangements.

Disabling lens shading isn't supported and is unlikely to produce a flat colour representation, and producing your own tables isn't supported either.

**Comment by rwb27** [comment]
Hello,
  I was wondering if there might have been any change on this since the camera module v2 came out - presumably there's a different lens shading correction for v1 and v2 of the camera module; is there now a way to switch between them?  
  I've been using the camera board in a microscope, where the optics really are pretty much uniform; the ability to turn off lens shading correction would be really nice (and much more elegant than the current hack of getting raw images and debarring them ourselves).  It would be great to keep the GPU-powered preview, video encoding, etc. etc. but just avoid the lens shading step.

Thanks in advance for any help,

Richard

**Comment by 6by9** [comment]
No, no change - it's a question of resourcing the change when very few people will make use of it.
The V2 camera uses an automatic lens shading algorithm, but then again so did the V1 to a lesser degree.

**Comment by rwb27** [comment]
Fair enough - thanks for the answer.  Perhaps with some experimentation I might be able to get the automatic lens shading to do the right thing - and if I do I'll certainly post it somewhere.

**Comment by 6by9** [comment]
Closing due to inactivity and al lfeatures requested are implemented.

You can now disable or provide an alternate lens shading grid - https://www.raspberrypi.org/forums/viewtopic.php?f=43&t=190586

Commit https://github.com/raspberrypi/userland/commit/212184f0f1fdf76eff31e3875fdeb2b7980cd5cb adds ```-ag <float>``` and ```-dg <float>``` options to the raspicam apps to fix the analogue and digital gains respectively.
It is using part of the AE/AGC algorithm, so do NOT set ```-ex off``` with these options.

If there is something specific that you find doesn't work with it, then please raise a new issue.
